heat_template_version: 2013-05-23

description: >
  HOT template to create EDX cluster

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: edx
  image:
    type: string
    description: Name of image to use for servers
    default: ubuntu-14.04-amd64
  medium:
    type: string
    description: Flavor to use
    default: m1.tiny
  large:
    type: string
    description: Flavor to use
    default: m1.small
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: public
  public_network_id:
    type: string
    description: >
      ID or name of public network id for which floating IP addresses will be allocated
    default: 86139c23-b2e3-428d-8a9a-7eb56b5085a1
  private1_net_name:
    type: string
    description: Name of private network to be created
    default: test-neutron-priv
  private1_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.101.0/24
  private1_net_gateway:
    type: string
    description: Private network gateway address
    default: 192.168.101.1
  private1_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 192.168.101.2
  private1_net_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 192.168.101.10
  private2_net_name:
    type: string
    description: Name of private network to be created
    default: test-neutron-priv
  private2_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.102.0/24
  private2_net_gateway:
    type: string
    description: Private network gateway address
    default: 192.168.102.1
  private2_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 192.168.102.2
  private2_net_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 192.168.102.10


resources:
  vpc1:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: vpc1.yaml
        properties:
          name: vpc1
          image:  { get_param: image }
          medium: { get_param: medium }
          large: { get_param: large }
          key_name: { get_param: key_name }
          public_net: { get_param: public_net }
          public_network_id: { get_param: public_network_id }
          private_net_name: { get_param: private1_net_name }
          private_net_cidr: { get_param: private1_net_cidr }
          private_net_gateway: { get_param: private1_net_gateway }
          private_net_pool_start: { get_param: private1_net_pool_start }
          private_net_pool_end: { get_param: private1_net_pool_end }
          
